---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 The Linux Foundation <mwatkins@linuxfoundation.org>

name: "Python Tests (Matrix)"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - "*"
      - "!update-devops-tooling"

jobs:
  ### EVALUATE TESTS REQUIRED ###

  evaluate:
    name: "Evaluate tests required"
    # Only run before PR is merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    outputs:
      pytest: ${{ steps.pytest.outputs.perform }}
      notebooks: ${{ steps.notebooks.outputs.perform }}
      versions: ${{ steps.determine.outputs.versions }}

    steps:
      - name: "Evaluate Python tests"
        id: pytest
        run: |
          RESULT1=(**/test_*.py)
          RESULT2=(**/*_test.py)
          if [ -z "${RESULT1[0]}" ] || [ -z "${RESULT2[0]}" ]; then
            echo "Found Python tests to perform"
            echo "perform=true" >> "$GITHUB_OUTPUT"
          fi

      - name: "Evaluate Notebook tests"
        id: notebooks
        run: |
          RESULT=(**/test_*.ipynb)
          if [ -z "${RESULT[0]}" ]; then
            echo "Found Jupyter Notebook tests"
            echo "proceed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: "Determine Python matrix versions"
        id: determine
        # yamllint disable-line rule:line-length
        uses: .github/actions/pyproject-extract-versions.yaml@main
